/* empty css                      */import{a as q,S as E,i as a}from"./assets/vendor-5YrzWRhu.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))m(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&m(n)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function m(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();const P="51708418-3aac8028d9e6ae6b223e03bd7",R="https://pixabay.com/api/",f=15;async function y(s,r=1){try{return(await q.get(R,{params:{key:P,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:f,page:r}})).data}catch(e){throw console.error("Pixabay API error:",e),e}}const h=document.querySelector(".gallery"),g=document.querySelector(".loader"),c=document.querySelector("#load-more"),B=new E(".gallery a",{captionsData:"alt",captionDelay:250});function b(s){const r=s.map(e=>`
    <li class="gallery-item">
      <a href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${e.likes}</p>
        <p><b>Views:</b> ${e.views}</p>
        <p><b>Comments:</b> ${e.comments}</p>
        <p><b>Downloads:</b> ${e.downloads}</p>
      </div>
    </li>
  `).join("");h.insertAdjacentHTML("beforeend",r),B.refresh()}function M(){h.innerHTML=""}function L(){g.classList.add("visible")}function v(){g.classList.remove("visible")}function $(){c.classList.remove("hidden"),c.disabled=!1}function w(){c.classList.add("hidden")}const S=document.querySelector("#search-form"),C=S.querySelector('input[name="searchQuery"]'),p=document.querySelector("#loading-message"),l=document.querySelector("#load-more");let d="",i=1,u=0;S.addEventListener("submit",async s=>{s.preventDefault();const r=C.value.trim();if(!r){a.warning({title:"Warning",message:"Please enter a search term!",position:"topRight"});return}M(),w(),d=r,i=1;try{L(),p.classList.add("visible");const e=await y(d,i);u=e.totalHits,e.hits.length?(b(e.hits),i*f<u&&$()):a.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}catch{a.error({title:"Error",message:"Failed to fetch images. Try again later.",position:"topRight"})}finally{v(),p.classList.remove("visible")}});l.addEventListener("click",async()=>{i+=1,L(),l.disabled=!0;try{const s=await y(d,i);b(s.hits),A(),i*f>=u?(w(),a.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):l.disabled=!1}catch{a.error({title:"Error",message:"Failed to fetch more images.",position:"topRight"})}finally{v()}});function A(){var e;if(!((e=document.querySelector(".gallery"))==null?void 0:e.firstElementChild))return;const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
